#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Wed Jul 22 10:43:22 CST 2026
maven-metadata-alimaven.xml.lastUpdated=1784688202792
maven-metadata-aliyunmaven.xml.lastUpdated=1784686551016
maven-metadata-sonatype-snapshots.xml.error=
maven-metadata-sonatype-snapshots.xml.lastUpdated=1784686551158
