#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Wed Jul 22 10:35:12 CST 2026
maven-metadata-alimaven.xml.lastUpdated=1784687712812
maven-metadata-aliyunmaven.xml.lastUpdated=1784686450612
maven-metadata-sonatype-snapshots.xml.error=
maven-metadata-sonatype-snapshots.xml.lastUpdated=1784686451221
